/**
 * Created by liujia on 2015/10/15.
 */

exports.LOAD_CONFIG_SUCCESS='LOAD_CONFIG_SUCCESS'
exports.INIT_CONFIG_SUCCESS='INIT_CONFIG_SUCCESS'
exports.SET_CONFIG_SUCCESS='SET_CONFIG_SUCCESS'
exports.RESTORE_CONFIG_SUCCESS='RESTORE_CONFIG_SUCCESS'

exports.LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
exports.LOAD_USER_FAILED='LOAD_USER_FAILED'
exports.LOGOUT='LOGOUT'

exports.LOAD_TOKEN_SUCCESS='LOAD_TOKEN_SUCCESS'
exports.CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS'
exports.CHECK_TOKEN_FAILED = 'CHECK_TOKEN_FAILED'

exports.UP_COMMENT_SUCCESS='UP_COMMENT_SUCCESS'
exports.LOAD_USERID_SUCCESS='LOAD_USERID_SUCCESS'

exports.GET_USER = 'GET_USER'


exports.GET_LOGIN_USER_FROM_STORAGE = 'GET_LOGIN_USER_FROM_STORAGE'
exports.GET_USER_FROM_STORAGE_FAILED = 'GET_USER_FROM_STORAGE_FAILED'
exports.FETCH_USER = 'FETCH_USER'

exports.OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL'
exports.CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL'
exports.LOGIN_SUCCESS = 'LOGIN_SUCCESS'
exports.QR_SUCCESS = 'QR_SUCCESS'

exports.LIKE_TOPIC = 'LIKE_TOPIC'
exports.UN_LIKE_TOPIC = 'UN_LIKE_TOPIC'

exports.CLEAR='CLEAR'


exports.GET_UNREAD_MESSAGE_COUNT_SUCCESS = 'GET_UNREAD_MESSAGE_COUNT_SUCCESS'
exports.GET_MESSAGES = 'GET_MESSAGES'
exports.FETCH_MESSAGES_FAILED = 'FETCH_MESSAGES_FAILED'
exports.FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST'
exports.FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS'
exports.MARK_AS_READ_SUCCESS = 'MARK_AS_READ_SUCCESS'
exports.MARK_AS_READ_FAILED = 'MARK_AS_READ_FAILED'
exports.MARK_AS_READ_REQUEST = 'MARK_AS_READ_REQUEST'


exports.GET_ALL_TOPICS_FROM_STORAGE = 'GET_ALL_TOPICS_FROM_STORAGE'
exports.FETCH_TOPICS_BY_TAB_REQUEST = 'FETCH_TOPICS_BY_TAB_REQUEST'
exports.FETCH_TOPICS_BY_TAB_SUCCESS = 'FETCH_TOPICS_BY_TAB_SUCCESS'
exports.FETCH_TOPICS_BY_TAB_FAILED = 'FETCH_TOPICS_BY_TAB_FAILED'


exports.GET_TOPICS = 'GET_TOPICS'
exports.UPDATE_TOPICS = 'UPDATE_TOPICS'

